import assert from 'node:assert/strict';
import { createCloud } from '../src/supabase.js';

const store = new Map();
const storage = { getItem: key => store.get(key) || null, setItem: (key, value) => store.set(key, value), removeItem: key => store.delete(key) };
const calls = [];
let failure = false;
const request = async (url, options) => {
  calls.push({ url, ...options });
  if (failure) return new Response(JSON.stringify({ message: 'rejected' }), { status: 403 });
  if (url.includes('/token')) return Response.json({ access_token: 'test-access', refresh_token: 'test-refresh', expires_in: 3600, user: { id: 'owner' } });
  if (url.endsWith('/user')) return Response.json({ id: 'owner' });
  return Response.json([{ quiz: { id: 'quiz' } }]);
};
const cloud = createCloud({ url: 'https://example.supabase.co', key: 'public-test', storage, fetch: request });
assert.equal(await cloud.restore(), null);
await cloud.signIn('owner@example.test', 'test-password');
assert.equal(cloud.user.id, 'owner');
await cloud.request('/rest/v1/foco_tests');
assert.equal(calls.at(-1).headers.Authorization, 'Bearer test-access');
await cloud.rpc('foco_public_test', { p_token: 'test-token' });
assert.equal(calls.at(-1).headers.Authorization, undefined, 'public RPC must not borrow evaluator session');
assert.equal(calls.at(-1).headers.apikey, 'public-test');
failure = true;
await assert.rejects(cloud.request('/rest/v1/foco_tests'), /rejected/);
assert.equal(cloud.user.id, 'owner', 'HTTP failure must not discard a valid session');
failure = false;
await cloud.signOut();
assert.equal(cloud.user, null);
assert.equal(store.size, 0);
const expired = { access_token: 'old', refresh_token: 'refresh', expires_at: 1, user: { id: 'owner' } };
storage.setItem('foco.auth.v1', JSON.stringify(expired));
const restored = createCloud({ url: 'https://example.supabase.co', key: 'public-test', storage, fetch: request });
assert.equal((await restored.restore()).id, 'owner');
assert.ok(calls.some(call => call.url.includes('grant_type=refresh_token')));
const offline = createCloud({ url: 'https://example.supabase.co', key: 'public-test', storage, fetch: async () => { throw new TypeError('offline'); } });
await assert.rejects(offline.restore(), /conexão/);
assert.ok(storage.getItem('foco.auth.v1'), 'network failure must preserve saved session');
storage.setItem('foco.auth.v1', JSON.stringify(expired));
let release;
const race = createCloud({ url: 'https://example.supabase.co', key: 'public-test', storage, fetch: async url => {
  if (url.includes('refresh_token')) return new Promise(resolve => { release = () => resolve(Response.json({ access_token: 'renewed', refresh_token: 'refresh', expires_in: 3600, user: { id: 'owner' } })); });
  return Response.json({ id: 'owner' });
} });
const restoring = race.restore();
await race.signOut();
release();
await assert.rejects(restoring, /sessão/);
assert.equal(race.user, null, 'late refresh must not undo logout');
console.log('Supabase HTTP: autenticação, renovação, RPC pública e falhas OK');
